function getReportCardHTML({ schoolName, student, subjects, term, feedbacks }) {
  const { name, grade, oen, homeroomTeacher } = student;

  const subjectRows = subjects.map((sub) => {
    const feedback = feedbacks.find(fb => fb.subject === sub.subject);
    const workHabits = feedback?.work_habits || '';
    const behavior = feedback?.behavior || '';
    const comment = feedback?.comment || '';

    return `
      <tr>
        <td style="padding: 10px; border: 1px solid #ccc;">${sub.subject}</td>
        <td style="padding: 10px; border: 1px solid #ccc; text-align: center;">${sub.grade}%</td>
        <td style="padding: 10px; border: 1px solid #ccc;">${workHabits}</td>
        <td style="padding: 10px; border: 1px solid #ccc;">${behavior}</td>
        <td style="padding: 10px; border: 1px solid #ccc;">${comment}</td>
      </tr>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <title>Report Card - ${name}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 40px;
          margin: 0;
        }
        .container {
          max-width: 750px;
          margin: auto;
          border: 1px solid #ccc;
          padding: 30px;
          border-radius: 8px;
        }
        h1, h2 {
          text-align: center;
          color: #048dca;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 25px;
        }
        th, td {
          padding: 10px;
          border: 1px solid #ccc;
        }
        .footer {
          text-align: center;
          margin-top: 50px;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>${schoolName}</h1>
        <h2>${term.toUpperCase()} REPORT CARD 2025–2026</h2>

        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Grade:</strong> ${grade}</p>
        <p><strong>OEN:</strong> ${oen}</p>
        <p><strong>Homeroom Teacher:</strong> ${homeroomTeacher}</p>

        <table>
          <thead>
            <tr>
              <th>Subject</th>
              <th>Final Grade</th>
              <th>Work Habits</th>
              <th>Behaviour</th>
              <th>Comment</th>
            </tr>
          </thead>
          <tbody>
            ${subjectRows}
          </tbody>
        </table>

        <div class="footer">
          Generated by School Mule
        </div>
      </div>
    </body>
    </html>
  `;
}

module.exports = { getReportCardHTML };
